version: '3'

services:
  application:
    container_name: application
    build: ./
    ports:
      - "80:3000/tcp"
    networks:
      - web
    links:
      - database
    restart: always

  database:
    container_name: database
    image: apache/couchdb
    networks:
      - web
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      - "COUCHDB_USER=${COUCHDB_USER}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD}"
    restart: always

  couchdb:
    container_name: couchdb
    image: apache/couchdb
    ports:
      - "5984:5984/tcp"
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      - "COUCHDB_USER=${COUCHDB_USER}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD}"

volumes:
  couchdb:
    external:
      name: couchdb

networks:
  web:
